version: 2.1

parameters:
  run-build-service-1-job:
    type: boolean
    default: false
  run-build-service-2-job:
    type: boolean
    default: false

jobs:
  build-and-push:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build services
          command: |
            - docker-compose up -d
      - when:
          condition: << pipeline.parameters.run-build-service-1-job >>
          steps:
            - run: echo "service_1_build"
      - when:
          condition: << pipeline.parameters.run-build-service-2-job >>
          steps:
            - run: echo "service_2_build"

workflows:
  version: 2
  build-all:
    jobs:
      - build-and-push
